language: python

sudo: false

install:
  - echo "Nothing to install"

script:
  - echo "TODO: add tests"

deploy:
  provider: pypi
  user: edx
  password:
    secure: ""
  distributions: sdist bdist_wheel
  on:
    tags: true
